### ISSUE TITLE
Have jenkins use the Debian testing repo instead of its own.

### ISSUE THREAD

**Issue by pgodschalk** [nulpunt/systems#9]

**Comment by GeertJohan** [comment]
I seriously doubt whether downgrading to testing is a good thing to do.
testing doesn't seem to have any patches on jenkins, and the main jenkins repo is updated directly with bugfixes and security patches. It looks a lot more 'stable' then the debian testing repo.

**Comment by GeertJohan** [comment]
http://packages.debian.org/search?keywords=jenkins
http://pkg.jenkins-ci.org/debian/
http://jenkins-ci.org/changelog

**Comment by pgodschalk** [comment]
The reason of running stable/testing is because there are no updates; only security patches get backported meaning stable/testing is always more stable than using latest from upstream.

**Comment by GeertJohan** [comment]
.513 release contains:
Fixed CSRF vulnerabilities (SECURITY-63,SECURITY-69)
Fixed an XSS vulnerability via stylesheet (SECURITY-67)
Fixed an XSS vulnerability to copy arbitrary text into clipboard (SECURITY-71/CVE-2013-1808) 

That was released 2013/05/18

Still not in debian testing (neither in unstable)...

**Comment by GeertJohan** [comment]
I've looked through the changelogs and arguments for the use of debian a bit more, but it doesn't seem like the debian team is putting any effort in backporting security fixes for jenkins at all. Perhaps because jenkins provides a good and stable repo?. I'll place my bet on the official jenkins repo, which is continiously maintained by engineers whose job is to create a system that tests systems..
